[project]
org-name= "wso2"
version= "0.9.0"
license= ["Apache-2.0"]
authors = ["WSO2"]
keywords = ["store forward", "message store message processor", "guaranteed delivery"]
repository = "https://github.com/wso2-ballerina/module-googlespreadsheet"

[dependencies]
